name: imc_segmentation
channels:
  - conda-forge
  - nvidia
  - bioconda
  - defaults

dependencies:
  - python=3.11
  - leidenalg
  - python-igraph
  - readimc
  - scanpy
  - scikit-image
  - bbknn
  - pyyaml
  - shapely
  - ipython
  - psutil
  - pip

  - pip:
      - openai==2.7.1
      - SpatialDM==0.3.1