name: imc_denoise
channels:
  - conda-forge
  - nvidia
  - defaults

dependencies:
  - python=3.8
  - cudatoolkit=11.2
  - cudnn=8.1
  - pyyaml
  - psutil
  - pip
  - pip:
      - numpy==1.19.5
      - pandas=1.1.5
      - scipy==1.4.1
      - matplotlib==3.3.4
      - scikit-learn==0.24.2
      - tensorflow==2.6.0
      - keras==2.6.0
      - tifffile==2023.7.10
      - protobuf==3.20.3
      - tqdm
      - IMC_Denoise @ git+https://github.com/couper-lab/IMC_Denoise_Updated
