name: athena
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python=3.8
    - anndata
    - colorcet
    - ipykernel
    - ipython
    - ipywidgets
    - matplotlib
    - networkx
    - numpy
    - pandas
    - pip
    - scanpy
    - scikit-image
    - scipy
    - seaborn
    - tqdm
    - pip:
        - ai4scr-athena
        - ai4scr-spatial-omics